-- Default options
-- Dark
-- local colors = {
-- 	_name = "modus_vivendi",
-- 	accent = "#79a8ff",
-- 	accent_dark = "#338fff",
-- 	accent_darker = "#2fafff",
-- 	accent_light = "#82b0ec",
-- 	bg_active = "#303030",
-- 	bg_added = "#00381f",
-- 	bg_added_faint = "#002910",
-- 	bg_added_fringe = "#237f3f",
-- 	bg_added_refine = "#034f2f",
-- 	bg_alt = "#0f0f0f",
-- 	bg_blue_intense = "#1640b0",
-- 	bg_blue_nuanced = "#0f0e39",
-- 	bg_blue_subtle = "#242679",
-- 	bg_changed = "#363300",
-- 	bg_changed_faint = "#2a1f00",
-- 	bg_changed_fringe = "#8a7a00",
-- 	bg_changed_refine = "#4a4a00",
-- 	bg_char_0 = "#0050af",
-- 	bg_char_1 = "#7f1f7f",
-- 	bg_char_2 = "#625a00",
-- 	bg_completion = "#2f447f",
-- 	bg_cyan_intense = "#2266ae",
-- 	bg_cyan_nuanced = "#041529",
-- 	bg_cyan_subtle = "#004065",
-- 	bg_diff_context = "#1a1a1a",
-- 	bg_dim = "#1e1e1e",
-- 	bg_green_intense = "#2f822f",
-- 	bg_green_nuanced = "#001904",
-- 	bg_green_subtle = "#00422a",
-- 	bg_hl_line = "#2f3849",
-- 	bg_inactive = "#282828",
-- 	bg_magenta_intense = "#7030af",
-- 	bg_magenta_nuanced = "#230631",
-- 	bg_magenta_subtle = "#552f5f",
-- 	bg_main = "#000000",
-- 	bg_paren_expression = "#453040",
-- 	bg_paren_match = "#2f7f9f",
-- 	bg_red_intense = "#9d1f1f",
-- 	bg_red_nuanced = "#2c0614",
-- 	bg_red_subtle = "#620f2a",
-- 	bg_removed = "#4f1119",
-- 	bg_removed_faint = "#380a0f",
-- 	bg_removed_fringe = "#b81a1f",
-- 	bg_removed_refine = "#781a1f",
-- 	bg_sidebar = "#1e1e1e",
-- 	bg_status_line_active = "#404040",
-- 	bg_status_line_inactive = "#2d2d2d",
-- 	bg_tab_alternate = "#545490",
-- 	bg_tab_bar = "#313131",
-- 	bg_tab_current = "#000000",
-- 	bg_tab_other = "#545454",
-- 	bg_yellow_intense = "#7a6100",
-- 	bg_yellow_nuanced = "#221000",
-- 	bg_yellow_subtle = "#4a4000",
-- 	blue = "#2fafff",
-- 	blue_cooler = "#00bcff",
-- 	blue_faint = "#82b0ec",
-- 	blue_intense = "#338fff",
-- 	blue_warmer = "#79a8ff",
-- 	border = "#646464",
-- 	border_highlight = "#C4C4C4",
-- 	comment = "#989898",
-- 	cursor = "#ffffff",
-- 	cyan = "#00d3d0",
-- 	cyan_cooler = "#6ae4b9",
-- 	cyan_faint = "#9ac8e0",
-- 	cyan_intense = "#00eff0",
-- 	cyan_warmer = "#4ae2f0",
-- 	deuteranopia_bg_added = "#003066",
-- 	deuteranopia_bg_added_faint = "#001a4f",
-- 	deuteranopia_bg_added_fringe = "#006fff",
-- 	deuteranopia_bg_added_refine = "#0f4a77",
-- 	deuteranopia_bg_changed = "#2f123f",
-- 	deuteranopia_bg_changed_faint = "#1f022f",
-- 	deuteranopia_bg_changed_fringe = "#7f55a0",
-- 	deuteranopia_bg_changed_refine = "#3f325f",
-- 	deuteranopia_bg_removed = "#3d3d00",
-- 	deuteranopia_bg_removed_faint = "#281f00",
-- 	deuteranopia_bg_removed_fringe = "#d0c03f",
-- 	deuteranopia_bg_removed_refine = "#555500",
-- 	deuteranopia_bg_status_line_active = "#2a2a6a",
-- 	deuteranopia_fg_added = "#c4d5ff",
-- 	deuteranopia_fg_added_intense = "#8080ff",
-- 	deuteranopia_fg_changed = "#e3cfff",
-- 	deuteranopia_fg_changed_intense = "#cf9fe2",
-- 	deuteranopia_fg_removed = "#d4d48f",
-- 	deuteranopia_fg_removed_intense = "#d0b05f",
-- 	deuteranopia_fg_status_line_active = "#f0f0f0",
-- 	deuteranopia_yellow = "#cabf00",
-- 	deuteranopia_yellow_cooler = "#d8af7a",
-- 	deuteranopia_yellow_warmer = "#ffa00f",
-- 	error = "#ff7f9f",
-- 	fg_active = "#f4f4f4",
-- 	fg_added = "#a0e0a0",
-- 	fg_added_intense = "#80e080",
-- 	fg_alt = "#c6daff",
-- 	fg_changed = "#efef80",
-- 	fg_changed_intense = "#c0b05f",
-- 	fg_dim = "#989898",
-- 	fg_inactive = "#bfc0c4",
-- 	fg_main = "#ffffff",
-- 	fg_removed = "#ffbfbf",
-- 	fg_removed_intense = "#ff9095",
-- 	fg_sidebar = "#ffffff",
-- 	fg_status_line_active = "#f0f0f0",
-- 	fg_status_line_inactive = "#969696",
-- 	fg_tab_other = "#f7f7f7",
-- 	gold = "#c0965b",
-- 	green = "#44bc44",
-- 	green_cooler = "#00c06f",
-- 	green_faint = "#88ca9f",
-- 	green_intense = "#44df44",
-- 	green_warmer = "#70b900",
-- 	hint = "#6ae4b9",
-- 	indigo = "#9099d9",
-- 	info = "#00bcff",
-- 	magenta = "#feacd0",
-- 	magenta_cooler = "#b6a0ff",
-- 	magenta_faint = "#caa6df",
-- 	magenta_intense = "#ff66ff",
-- 	magenta_warmer = "#f78fe7",
-- 	maroon = "#cf7fa7",
-- 	none = "NONE",
-- 	olive = "#9cbd6f",
-- 	pink = "#d09dc0",
-- 	red = "#ff5f59",
-- 	red_cooler = "#ff7f9f",
-- 	red_faint = "#ff9580",
-- 	red_intense = "#ff5f5f",
-- 	red_warmer = "#ff6b55",
-- 	rust = "#db7b5f",
-- 	slate = "#76afbf",
-- 	success = "#a0e0a0",
-- 	tinted_bg_active = "#4a4f69",
-- 	tinted_bg_added = "#003a2f",
-- 	tinted_bg_added_faint = "#002922",
-- 	tinted_bg_added_fringe = "#23884f",
-- 	tinted_bg_added_refine = "#035542",
-- 	tinted_bg_blue_nuanced = "#131c4d",
-- 	tinted_bg_changed_fringe = "#8f7a30",
-- 	tinted_bg_completion = "#483d8a",
-- 	tinted_bg_cyan_nuanced = "#04253f",
-- 	tinted_bg_diff_context = "#1a1f30",
-- 	tinted_bg_dim = "#1d2235",
-- 	tinted_bg_green_nuanced = "#002718",
-- 	tinted_bg_hl_line = "#303a6f",
-- 	tinted_bg_inactive = "#2b3045",
-- 	tinted_bg_magenta_nuanced = "#2f133f",
-- 	tinted_bg_main = "#0d0e1c",
-- 	tinted_bg_paren_match = "#2f7f9f",
-- 	tinted_bg_red_nuanced = "#350f14",
-- 	tinted_bg_removed = "#4f1127",
-- 	tinted_bg_removed_faint = "#380a19",
-- 	tinted_bg_removed_fringe = "#b81a26",
-- 	tinted_bg_removed_refine = "#781a3a",
-- 	tinted_bg_status_line_active = "#393F51",
-- 	tinted_bg_status_line_inactive = "#292d48",
-- 	tinted_bg_tab_alternate = "#4a4f94",
-- 	tinted_bg_tab_bar = "#2c3045",
-- 	tinted_bg_tab_current = "#0d0e1c",
-- 	tinted_bg_tab_other = "#4a4f6a",
-- 	tinted_bg_yellow_nuanced = "#2c1f00",
-- 	tinted_border = "#61647a",
-- 	tinted_border_highlight = "#b290b0",
-- 	tinted_red_faint = "#ff9f80",
-- 	tritanopia_bg_added = "#004254",
-- 	tritanopia_bg_added_faint = "#003042",
-- 	tritanopia_bg_added_fringe = "#008fcf",
-- 	tritanopia_bg_added_refine = "#004f7f",
-- 	tritanopia_bg_changed = "#2f123f",
-- 	tritanopia_bg_changed_faint = "#1f022f",
-- 	tritanopia_bg_changed_fringe = "#7f55a0",
-- 	tritanopia_bg_changed_refine = "#3f325f",
-- 	tritanopia_bg_char_0 = "#922a00",
-- 	tritanopia_bg_char_1 = "#00709f",
-- 	tritanopia_bg_char_2 = "#5f3faf",
-- 	tritanopia_bg_completion = "#004253",
-- 	tritanopia_bg_hl_line = "#2f3849",
-- 	tritanopia_bg_status_line_active = "#003c52",
-- 	tritanopia_cyan_faint = "#7fdbdf",
-- 	tritanopia_cyan_warmer = "#4ae2ff",
-- 	tritanopia_fg_added = "#9fdfdf",
-- 	tritanopia_fg_added_intense = "#50c0ef",
-- 	tritanopia_fg_changed = "#e3cfff",
-- 	tritanopia_fg_changed_intense = "#cf9fe2",
-- 	tritanopia_fg_status_line_active = "#f0f0f0",
-- 	tritanopia_magenta_intense = "#ef7fff",
-- 	tritanopia_red_cooler = "#ff6f9f",
-- 	tritanopia_red_faint = "#ff9070",
-- 	tritanopia_red_warmer = "#ff6740",
-- 	tritanopia_yellow = "#cabf00",
-- 	tritanopia_yellow_cooler = "#d8af7a",
-- 	tritanopia_yellow_warmer = "#ffa00f",
-- 	visual = "#7030af",
-- 	warning = "#dfaf7a",
-- 	yellow = "#d0bc00",
-- 	yellow_cooler = "#dfaf7a",
-- 	yellow_faint = "#d2b580",
-- 	yellow_intense = "#efef00",
-- 	yellow_warmer = "#fec43f",
-- }
-- Light
local colors = {
	_name = "modus_operandi",
	accent = "#3548cf",
	accent_dark = "#0000ff",
	accent_darker = "#0031a9",
	accent_light = "#003497",
	bg_active = "#e0e0e0",
	bg_added = "#c1f2d1",
	bg_added_faint = "#d8f8e1",
	bg_added_fringe = "#6cc06c",
	bg_added_refine = "#aee5be",
	bg_alt = "#f0f0f0",
	bg_blue_intense = "#bfc9ff",
	bg_blue_nuanced = "#f3f3ff",
	bg_blue_subtle = "#ccdfff",
	bg_changed = "#ffdfa9",
	bg_changed_faint = "#ffefbf",
	bg_changed_fringe = "#d7c20a",
	bg_changed_refine = "#fac090",
	bg_char_0 = "#7feaff",
	bg_char_1 = "#ffaaff",
	bg_char_2 = "#dff000",
	bg_completion = "#c0deff",
	bg_cyan_intense = "#a4d5f9",
	bg_cyan_nuanced = "#ebf6fa",
	bg_cyan_subtle = "#bfefff",
	bg_diff_context = "#f3f3f3",
	bg_dim = "#f2f2f2",
	bg_green_intense = "#8adf80",
	bg_green_nuanced = "#ecf7ed",
	bg_green_subtle = "#b3fabf",
	bg_hl_line = "#d0d6ec",
	bg_inactive = "#e9e9e9",
	bg_magenta_intense = "#dfa0f0",
	bg_magenta_nuanced = "#fdf0ff",
	bg_magenta_subtle = "#ffddff",
	bg_main = "#ffffff",
	bg_paren_expression = "#efd3f5",
	bg_paren_match = "#5fcfff",
	bg_red_intense = "#ff8f88",
	bg_red_nuanced = "#fff1f0",
	bg_red_subtle = "#ffcfbf",
	bg_removed = "#ffd8d5",
	bg_removed_faint = "#ffe9e9",
	bg_removed_fringe = "#d84a4f",
	bg_removed_refine = "#f3b5af",
	bg_sidebar = "#f2f2f2",
	bg_status_line_active = "#c8c8c8",
	bg_status_line_inactive = "#e6e6e6",
	bg_tab_alternate = "#c2c2e8",
	bg_tab_bar = "#dfdfdf",
	bg_tab_current = "#ffffff",
	bg_tab_other = "#c2c2c2",
	bg_yellow_intense = "#f3d000",
	bg_yellow_nuanced = "#fff3da",
	bg_yellow_subtle = "#fff576",
	blue = "#0031a9",
	blue_cooler = "#0000b0",
	blue_faint = "#003497",
	blue_intense = "#0000ff",
	blue_warmer = "#3548cf",
	border = "#9f9f9f",
	border_highlight = "#3b3b3b",
	comment = "#595959",
	cursor = "#000000",
	cyan = "#005e8b",
	cyan_cooler = "#005f5f",
	cyan_faint = "#005077",
	cyan_intense = "#008899",
	cyan_warmer = "#3f578f",
	deuteranopia_bg_added = "#d5d7ff",
	deuteranopia_bg_added_faint = "#e6e6ff",
	deuteranopia_bg_added_fringe = "#275acc",
	deuteranopia_bg_added_refine = "#babcef",
	deuteranopia_bg_changed = "#eecfdf",
	deuteranopia_bg_changed_faint = "#f0dde5",
	deuteranopia_bg_changed_fringe = "#9f6ab0",
	deuteranopia_bg_changed_refine = "#e0b0d0",
	deuteranopia_bg_removed = "#f4f099",
	deuteranopia_bg_removed_faint = "#f6f6b7",
	deuteranopia_bg_removed_fringe = "#c0b200",
	deuteranopia_bg_removed_refine = "#ede06f",
	deuteranopia_bg_status_line_active = "#d0d6ff",
	deuteranopia_fg_added = "#303099",
	deuteranopia_fg_added_intense = "#0303cc",
	deuteranopia_fg_changed = "#6f1343",
	deuteranopia_fg_changed_intense = "#7f0f9f",
	deuteranopia_fg_removed = "#553d00",
	deuteranopia_fg_removed_intense = "#7f6f00",
	deuteranopia_fg_status_line_active = "#0f0f0f",
	deuteranopia_yellow = "#695500",
	deuteranopia_yellow_cooler = "#77492f",
	deuteranopia_yellow_warmer = "#973300",
	error = "#a0132f",
	fg_active = "#0a0a0a",
	fg_added = "#005000",
	fg_added_intense = "#006700",
	fg_alt = "#193668",
	fg_changed = "#553d00",
	fg_changed_intense = "#655000",
	fg_dim = "#595959",
	fg_inactive = "#404148",
	fg_main = "#000000",
	fg_removed = "#8f1313",
	fg_removed_intense = "#aa2222",
	fg_sidebar = "#000000",
	fg_status_line_active = "#0a0a0a",
	fg_status_line_inactive = "#585858",
	fg_tab_other = "#333333",
	gold = "#80601f",
	green = "#006800",
	green_cooler = "#00663f",
	green_faint = "#2a5045",
	green_intense = "#008900",
	green_warmer = "#316500",
	hint = "#005f5f",
	indigo = "#4a3a8a",
	info = "#0000b0",
	magenta = "#721045",
	magenta_cooler = "#531ab6",
	magenta_faint = "#7c318f",
	magenta_intense = "#dd22dd",
	magenta_warmer = "#8f0075",
	maroon = "#731c52",
	none = "NONE",
	olive = "#56692d",
	pink = "#7b435c",
	red = "#a60000",
	red_cooler = "#a0132f",
	red_faint = "#7f0000",
	red_intense = "#d00000",
	red_warmer = "#972500",
	rust = "#8a290f",
	slate = "#2f3f83",
	success = "#005000",
	tinted_bg_active = "#c9b9b0",
	tinted_bg_added = "#c3ebc1",
	tinted_bg_added_faint = "#dcf8d1",
	tinted_bg_added_fringe = "#6cc06c",
	tinted_bg_added_refine = "#acd6a5",
	tinted_bg_blue_nuanced = "#ebebff",
	tinted_bg_changed_fringe = "#c0b200",
	tinted_bg_completion = "#f0c1cf",
	tinted_bg_cyan_nuanced = "#e1f3fc",
	tinted_bg_diff_context = "#efe9df",
	tinted_bg_dim = "#efe9dd",
	tinted_bg_green_nuanced = "#e0f5e0",
	tinted_bg_hl_line = "#f1d5d0",
	tinted_bg_inactive = "#dfd5cf",
	tinted_bg_magenta_nuanced = "#f6e7ff",
	tinted_bg_main = "#fbf7f0",
	tinted_bg_paren_match = "#7fdfcf",
	tinted_bg_red_nuanced = "#ffe8f0",
	tinted_bg_removed = "#f4d0cf",
	tinted_bg_removed_faint = "#ffe9e5",
	tinted_bg_removed_fringe = "#d84a4f",
	tinted_bg_removed_refine = "#f3b5a7",
	tinted_bg_status_line_active = "#cab9b2",
	tinted_bg_status_line_inactive = "#dfd9cf",
	tinted_bg_tab_alternate = "#c8b8ca",
	tinted_bg_tab_bar = "#e0d4ce",
	tinted_bg_tab_current = "#fbf7f0",
	tinted_bg_tab_other = "#c8b8b2",
	tinted_bg_yellow_nuanced = "#f9ead0",
	tinted_border = "#9f9690",
	tinted_border_highlight = "#5c3f3d",
	tinted_red_faint = "#7f0000",
	tritanopia_bg_added = "#b5e7ff",
	tritanopia_bg_added_faint = "#c6f6ff",
	tritanopia_bg_added_fringe = "#1782cc",
	tritanopia_bg_added_refine = "#9adcef",
	tritanopia_bg_changed = "#eecfdf",
	tritanopia_bg_changed_faint = "#f0dde5",
	tritanopia_bg_changed_fringe = "#9f6ab0",
	tritanopia_bg_changed_refine = "#e0b0d0",
	tritanopia_bg_char_0 = "#ff908f",
	tritanopia_bg_char_1 = "#bfbfff",
	tritanopia_bg_char_2 = "#5fcfdf",
	tritanopia_bg_completion = "#afdfef",
	tritanopia_bg_hl_line = "#dfeaec",
	tritanopia_bg_status_line_active = "#afe0f2",
	tritanopia_cyan_faint = "#004f5f",
	tritanopia_cyan_warmer = "#3f578f",
	tritanopia_fg_added = "#005079",
	tritanopia_fg_added_intense = "#0043aa",
	tritanopia_fg_changed = "#6f1343",
	tritanopia_fg_changed_intense = "#7f0f9f",
	tritanopia_fg_status_line_active = "#0f0f0f",
	tritanopia_magenta_intense = "#cd22bd",
	tritanopia_red_cooler = "#a0132f",
	tritanopia_red_faint = "#702000",
	tritanopia_red_warmer = "#b21100",
	tritanopia_yellow = "#695500",
	tritanopia_yellow_cooler = "#77492f",
	tritanopia_yellow_warmer = "#973300",
	visual = "#dfa0f0",
	warning = "#7a4f2f",
	yellow = "#6f5500",
	yellow_cooler = "#7a4f2f",
	yellow_faint = "#624416",
	yellow_intense = "#808000",
	yellow_warmer = "#884900",
}

---@diagnostic disable: inject-field
require("modus-themes").setup({
	-- Theme comes in two styles `modus_operandi` and `modus_vivendi`
	-- `auto` will automatically set style based on background set with vim.o.background
	style = "auto",
	variant = "default", -- Theme comes in four variants `default`, `tinted`, `deuteranopia`, and `tritanopia`
	transparent = false, -- Transparent background (as supported by the terminal)
	dim_inactive = false, -- "non-current" windows are dimmed
	hide_inactive_statusline = false, -- Hide statuslines on inactive windows. Works with the standard **StatusLine**, **LuaLine** and **mini.statusline**
	styles = {
		-- Style to be applied to different syntax groups
		-- Value is any valid attr-list value for `:help nvim_set_hl`
		comments = {},
		keywords = { italic = true },
		functions = { bold = true },
		variables = {},
	},

	--- Refer to `extras/lua/modus_operandi.lua` or `extras/lua/modus_vivendi.lua` for the ColorScheme table
	---@param colors ColorScheme
	on_colors = function(colors)
		colors.bg0 = "#1d2021"
		colors.bg = "#282828"
	end,

	--- Refer to `extras/lua/modus_operandi.lua` or `extras/lua/modus_vivendi.lua` for the Highlights and ColorScheme table
	---@param highlights Highlights
	---@param theme_colors ColorScheme
	on_highlights = function(highlights, theme_colors) ---@diagnostic disable-line: unused-local
		-- -- General
		highlights.LineNr = { fg = colors.comment }
		highlights.Normal = { bg = colors.bg0 }
		highlights.NormalNC = { bg = colors.bg0 }
		highlights.WinBar = { bg = colors.bg0 }
		highlights.WinBarNC = { bg = colors.bg0 }

		highlights.String = { fg = colors.yellow_warmer }
		-- highlights.Identifier = { fg = colors.fg_active }

		-- LSP
		highlights["@comment"] = { fg = colors.comment, italic = false }
		highlights["@lsp.type.comment"] = { fg = colors.comment, italic = false }

		-- Gitsigns
		highlights.CursorLineNr = { fg = colors.fg_active, bg = colors.bg0, bold = true }
		highlights.FloatBorder = { fg = colors.comment, bg = colors.bg0 }
		highlights.SignColumn = { bg = colors.bg0 }
		highlights.WinSeparator = { bg = colors.border }

		-- Telescope
		highlights.TelescopeBorder = { fg = colors.comment, bg = colors.bg0 }
		highlights.TelescopePromptBorder = { fg = colors.comment, bg = colors.bg0 }
		highlights.TelescopePromptTitle = { bg = colors.bg0 }
		highlights.TelescopeTitle = { bg = colors.bg0 }
	end,
})
